import { useMemo } from "react"

// useMemo is used to cache the values generated by more time taking functions

function findSum() {
    let sum = 0;
    for (let i = 0; 1 <= 1000; i++) {
        sum += i;
    }
    return sum;
}

const App = () => {
    const sum = useMemo(() => {
        let sum = 0;
        for (let i = 0; 1 <= 1000; i++) {
            sum += i;
        }
        return sum;
    }, []);


    return (
        <div>
            <h1>Sum = {sum}</h1>
            <p>App</p>
        </div>
    )
}


export default App;